<a href="https://colab.research.google.com/github/veranika-izrailyan/Machine_Learning/blob/main/Dataset_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y
  def __len__(self):
    """
    Returns the total number of samples available in our dataset
    """
    return len(self.X)
  def __getitem__(self, idx):
    """
    Retruns a sample of data at precise idx
    """
    return(self.X[idx], self.y[idx])

In [7]:
from sklearn.datasets import make_classification

In [8]:
data, target = make_classification(n_samples=1000, n_features=5)
custom_dataset = CustomDataset(X=data, y=target)
len(custom_dataset)

1000

In [9]:
custom_dataset[0]

(array([-2.19141143, -0.43760535,  0.09458157,  1.32587649, -0.90073051]), 0)

In [10]:
data[0]

array([-2.19141143, -0.43760535,  0.09458157,  1.32587649, -0.90073051])

In [11]:
custom_dataset[0][0].shape

(5,)

In [14]:
from sklearn.datasets import make_multilabel_classification

data, target = make_multilabel_classification(n_samples=1000, n_features=5, n_classes=3)

In [15]:
custom_dataset_mlb=CustomDataset(X=data, y=target)

In [16]:
custom_dataset_mlb[0]

(array([ 2.,  6.,  3.,  2., 28.]), array([0, 1, 1]))

In [20]:
custom_dataset_mlb[3]

(array([ 5., 19.,  0.,  7., 22.]), array([0, 0, 1]))

In [21]:
from torch.utils.data import DataLoader

In [22]:
data_loader=DataLoader(dataset=custom_dataset, batch_size=8, shuffle=True)

In [23]:
custom_dataset[0]

(array([-2.19141143, -0.43760535,  0.09458157,  1.32587649, -0.90073051]), 0)

In [24]:
data_iter = iter(data_loader)
data_iter

In [25]:
data_02 = data_iter.next()

In [28]:
features_02, target_02 =data_02

In [29]:
features_02

tensor([[-2.0834, -0.4018,  0.0722,  1.2535,  1.7245],
        [ 0.6348,  2.1605, -2.5603, -1.3914, -1.1247],
        [ 3.0971,  2.9294, -3.0118, -3.0184,  0.0259],
        [-3.2877, -1.6333,  1.3584,  2.4730,  0.6665],
        [ 1.0779, -0.2503,  0.5333, -0.4216, -0.6411],
        [ 2.8924,  2.6281, -2.6786, -2.7656, -0.5310],
        [ 2.2269,  1.6585, -1.6079, -1.9486, -0.6088],
        [ 1.0928, -1.0025,  1.4731, -0.0565, -1.2280]], dtype=torch.float64)