<a href="https://colab.research.google.com/github/veranika-izrailyan/Machine_Learning/blob/main/Dealing_with_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
data_fake = pd.DataFrame(
    {
        'items':[np.nan,2,4,8,10],
        'age':[23,np.nan,28,32,40],
        'cost':[9500,11000,np.nan,np.nan,14760]
    },
)
data_fake

items   age     cost
0    NaN  23.0   9500.0
1    2.0   NaN  11000.0
2    4.0  28.0      NaN
3    8.0  32.0      NaN
4   10.0  40.0  14760.0

In [2]:
# Simple imputer (Univariate)

from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan, strategy='median')
imp.fit_transform(data_fake)

array([[6.000e+00, 2.300e+01, 9.500e+03],
       [2.000e+00, 3.000e+01, 1.100e+04],
       [4.000e+00, 2.800e+01, 1.100e+04],
       [8.000e+00, 3.200e+01, 1.100e+04],
       [1.000e+01, 4.000e+01, 1.476e+04]])

In [3]:
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit_transform(data_fake)

array([[6.00000000e+00, 2.30000000e+01, 9.50000000e+03],
       [2.00000000e+00, 3.07500000e+01, 1.10000000e+04],
       [4.00000000e+00, 2.80000000e+01, 1.17533333e+04],
       [8.00000000e+00, 3.20000000e+01, 1.17533333e+04],
       [1.00000000e+01, 4.00000000e+01, 1.47600000e+04]])

In [5]:
imp_mean=SimpleImputer(missing_values=np.nan, strategy='mean',add_indicator=True)
pd.DataFrame(imp_mean.fit_transform(data_fake))

0      1             2    3    4    5
0   6.0  23.00   9500.000000  1.0  0.0  0.0
1   2.0  30.75  11000.000000  0.0  1.0  0.0
2   4.0  28.00  11753.333333  0.0  0.0  1.0
3   8.0  32.00  11753.333333  0.0  0.0  1.0
4  10.0  40.00  14760.000000  0.0  0.0  0.0

In [6]:
# Multivariate imputers
# Iterative imputer

from sklearn.experimental import enable_iterative_imputer

In [8]:
from sklearn.impute import IterativeImputer

In [9]:
it=IterativeImputer()
it.fit_transform(data_fake)

array([[9.94732358e-01, 2.30000000e+01, 9.50000000e+03],
       [2.00000000e+00, 2.78460143e+01, 1.10000000e+04],
       [4.00000000e+00, 2.80000000e+01, 1.10469250e+04],
       [8.00000000e+00, 3.20000000e+01, 1.22838660e+04],
       [1.00000000e+01, 4.00000000e+01, 1.47600000e+04]])

In [10]:
# K-NN imputer
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=2)
knn.fit_transform(data_fake)

array([[6.000e+00, 2.300e+01, 9.500e+03],
       [2.000e+00, 3.000e+01, 1.100e+04],
       [4.000e+00, 2.800e+01, 1.025e+04],
       [8.000e+00, 3.200e+01, 1.288e+04],
       [1.000e+01, 4.000e+01, 1.476e+04]])