<a href="https://colab.research.google.com/github/veranika-izrailyan/Machine_Learning/blob/main/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Autograd Module**



*   **Forward Propagation**
      Compute the loss based on inputs
*   **Backward Propagation**
      Compute the gradient of the cost function wrt the inputs




In [1]:
import torch

In [3]:
x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376])

In [4]:
loss = x**2 - 5

In [6]:
# forward propagation
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986])

In [7]:
# backward

x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376], requires_grad=True)

In [8]:
loss = x**2 - 5
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986], grad_fn=<SubBackward0>)

In [9]:
loss.grad_fn

In [10]:
# Computing the gradient

loss.backward(gradient=torch.ones(5))

In [11]:
x.grad

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752])

In [12]:
2 * x

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752], grad_fn=<MulBackward0>)

In [14]:
# preventing PyTorch from keeping the history of gradients

a = torch.rand(2,2, requires_grad=True)

b = a.detach()
b.requires_grad


False

In [15]:
# or
c = torch.rand(2,2, requires_grad=True)

with torch.no_grad():
  loss = c**2
  print(loss.requires_grad)

False
