<a href="https://colab.research.google.com/github/veranika-izrailyan/Machine_Learning/blob/main/Tensors_in__PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_data=[[1,3], [3,4]]
torch.tensor(my_data)

tensor([[1, 3],
        [3, 4]])

In [4]:
my_tensor = torch.tensor(my_data)
my_tensor.dtype

torch.int64

In [5]:
my_tensor.type()

'torch.LongTensor'

In [6]:
my_tensor.device

device(type='cpu')

In [7]:
my_tensor.to('cuda')

tensor([[1, 3],
        [3, 4]], device='cuda:0')

In [8]:
torch.cuda.current_device()

0

In [9]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
new_tensor = torch.ones((2,2))
new_tensor.dtype

torch.float32

In [13]:
new_tensor.type()

'torch.FloatTensor'

In [14]:
updated_tensor = new_tensor.new_tensor(my_data)
updated_tensor.dtype

torch.float32

In [18]:
another_tensor = torch.ones((2,2), dtype=torch.int8, device = 'cuda')

In [16]:
another_tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

In [19]:
another_tensor.new_tensor(my_data)

tensor([[1, 3],
        [3, 4]], device='cuda:0', dtype=torch.int8)

In [20]:
another_tensor.device

device(type='cuda', index=0)

In [21]:
new_data=[[1,2],[3,4],[5,6]]
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0', dtype=torch.int8)

In [26]:
shape= (2,3,)
my_tensor = torch.rand(shape)

In [27]:
my_tensor

tensor([[0.0758, 0.5621, 0.0894],
        [0.7607, 0.3970, 0.0588]])

In [28]:
torch.rand_like(my_tensor, dtype=torch.float)

tensor([[0.1134, 0.0617, 0.0159],
        [0.5196, 0.0301, 0.9909]])