<a href="https://colab.research.google.com/github/veranika-izrailyan/Machine_Learning/blob/main/Tensors_in__PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_data=[[1,3], [3,4]]
torch.tensor(my_data)

tensor([[1, 3],
        [3, 4]])

In [4]:
my_tensor = torch.tensor(my_data)
my_tensor.dtype

torch.int64

In [5]:
my_tensor.type()

'torch.LongTensor'

In [6]:
my_tensor.device

device(type='cpu')

In [7]:
my_tensor.to('cuda')

tensor([[1, 3],
        [3, 4]], device='cuda:0')

In [8]:
torch.cuda.current_device()

0

In [9]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
new_tensor = torch.ones((2,2))
new_tensor.dtype

torch.float32

In [13]:
new_tensor.type()

'torch.FloatTensor'

In [14]:
updated_tensor = new_tensor.new_tensor(my_data)
updated_tensor.dtype

torch.float32

In [18]:
another_tensor = torch.ones((2,2), dtype=torch.int8, device = 'cuda')

In [16]:
another_tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

In [19]:
another_tensor.new_tensor(my_data)

tensor([[1, 3],
        [3, 4]], device='cuda:0', dtype=torch.int8)

In [20]:
another_tensor.device

device(type='cuda', index=0)

In [21]:
new_data=[[1,2],[3,4],[5,6]]
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0', dtype=torch.int8)

In [26]:
shape= (2,3,)
my_tensor = torch.rand(shape)

In [27]:
my_tensor

tensor([[0.0758, 0.5621, 0.0894],
        [0.7607, 0.3970, 0.0588]])

In [28]:
torch.rand_like(my_tensor, dtype=torch.float)

tensor([[0.1134, 0.0617, 0.0159],
        [0.5196, 0.0301, 0.9909]])

In [29]:
import numpy as np
numpy_data = np.random.rand(2,3)
numpy_data

array([[0.25321279, 0.98743772, 0.38447809],
       [0.86348559, 0.05177233, 0.27822916]])

In [31]:
torch_numpy = torch.from_numpy(numpy_data)
torch_numpy

tensor([[0.2532, 0.9874, 0.3845],
        [0.8635, 0.0518, 0.2782]], dtype=torch.float64)

In [32]:
tensor_numpy_direct = torch.tensor(numpy_data)
tensor_numpy_direct

tensor([[0.2532, 0.9874, 0.3845],
        [0.8635, 0.0518, 0.2782]], dtype=torch.float64)

In [34]:
tensor_numpy_direct.cpu().numpy()

array([[0.25321279, 0.98743772, 0.38447809],
       [0.86348559, 0.05177233, 0.27822916]])

**Operations between tensors**

In [36]:
numpy_data = np.random.rand(2,3)
numpy_data

array([[0.67142347, 0.82363784, 0.16076046],
       [0.38978236, 0.99157473, 0.05041279]])

In [37]:
my_tns2 = torch.tensor(numpy_data)
my_tns2

tensor([[0.6714, 0.8236, 0.1608],
        [0.3898, 0.9916, 0.0504]], dtype=torch.float64)

In [38]:
my_tns1 = torch_numpy
my_tns1

tensor([[0.2532, 0.9874, 0.3845],
        [0.8635, 0.0518, 0.2782]], dtype=torch.float64)

In [39]:
# concatenation
torch.cat([my_tns1, my_tns2], dim=0)


tensor([[0.2532, 0.9874, 0.3845],
        [0.8635, 0.0518, 0.2782],
        [0.6714, 0.8236, 0.1608],
        [0.3898, 0.9916, 0.0504]], dtype=torch.float64)

In [40]:
torch.cat([my_tns1, my_tns2], dim=1)

tensor([[0.2532, 0.9874, 0.3845, 0.6714, 0.8236, 0.1608],
        [0.8635, 0.0518, 0.2782, 0.3898, 0.9916, 0.0504]], dtype=torch.float64)

In [41]:
# adding lower and upper bounds

my_tns2.clip(0.3,0.7)

tensor([[0.6714, 0.7000, 0.3000],
        [0.3898, 0.7000, 0.3000]], dtype=torch.float64)

In [42]:
# element-wise multiplication

my_tns1.mul(my_tns2)

tensor([[0.1700, 0.8133, 0.0618],
        [0.3366, 0.0513, 0.0140]], dtype=torch.float64)

In [43]:
my_tns1*my_tns2

tensor([[0.1700, 0.8133, 0.0618],
        [0.3366, 0.0513, 0.0140]], dtype=torch.float64)

In [44]:
# matrix multiplication

my_tns1.matmul(my_tns2.T)

tensor([[1.0451, 1.0972],
        [0.6671, 0.4019]], dtype=torch.float64)

In [45]:
my_tns1 @ my_tns2.T

tensor([[1.0451, 1.0972],
        [0.6671, 0.4019]], dtype=torch.float64)

In [46]:
my_sum = my_tns2.sum()
my_sum

tensor(3.0876, dtype=torch.float64)

In [47]:
my_sum.item()

3.087591648847689

In [48]:
type(my_sum.item())

float

In [50]:
# create grid of integers
torch.arange(20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [55]:
matrix_A=torch.arange(20, dtype=torch.float32).reshape(5,4)
matrix_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [56]:
matrix_B = matrix_A.clone()

In [57]:
matrix_A + matrix_B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [58]:
matrix_B.mean()

tensor(9.5000)

In [59]:
matrix_B.mean(dim=0)

tensor([ 8.,  9., 10., 11.])

In [60]:
matrix_B.sum(axis=0)/matrix_B.shape[0]

tensor([ 8.,  9., 10., 11.])